doc_srcdir := $(top_srcdir)/doc

# XML DocBook output
 
%.html: %.docbook $(FIGS:.fig=.png) $(doc_srcdir)/sailcut-html.xsl
	$(XSLTPROC) -o $@ $(doc_srcdir)/sailcut-html.xsl $<

%.pdf: %.docbook $(FIGS)
	$(DBLATEX) -o $@ $<

# XFig graphics conversions

%.png: %.fig
	$(FIG2DEV) -L png -S2 $^ $@

%.svg: %.fig
	$(FIG2DEV) -L svg $^ $@

