#!/bin/sh
FIGURES="coordinates_system sailplan sail_seams sail_edges develop_panel_drawing head_gores_definition rigplan"
for lang in en es fr; do
    /usr/bin/xsltproc -o $lang/index.html sailcut-html.xsl $lang/index.docbook
    for fig in $FIGURES; do
        /usr/bin/fig2dev -L png -S2 $lang/$fig.fig $lang/$fig.png
    done
done
