doc_srcdir := $(top_srcdir)/doc

# XML DocBook output
 
%.html: %.docbook $(FIGS:.fig=.png) $(doc_srcdir)/sailcut-html.xsl
	$(XSLTPROC) -o $@ $(doc_srcdir)/sailcut-html.xsl $<

# XFig graphics conversions

%.png: %.fig
	$(FIG2DEV) -L png -S2 $^ $@

