CC=g++

CPPFLAGS=-g -Wall

OBJECTS=core.o vect_real.o vect_geom.o matrix.o subspace.o geotest.o
TARGET=geotest

all: $(TARGET)

%.o: %.cpp  %.h 
	$(CC) $(CPPFLAGS) -c -o $@ $<

$(TARGET): $(OBJECTS)
	$(CC) -o $(TARGET) $(OBJECTS)

clean:
	rm -f $(OBJECTS) $(TARGET)
