name: tests

on: [push, pull_request]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
            arch: win64_mingw
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v4
        with:
          arch: ${{ matrix.arch }}
          version: 6.5.*
      - uses: msys2/setup-msys2@v2
        if: matrix.os == 'windows-latest'
        with:
          install: mingw-w64-x86_64-nsis
      - name: Compile
        run: |
          qmake
          make
        shell: bash
      - name: Test
        run: make check --keep-going
        shell: bash
      - name: Build package
        if: matrix.os != 'ubuntu-latest'
        run: make package
      - name: Upload package
        if: matrix.os != 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: sailcut-*
