name: tests

on: [push, pull_request]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
            arch: win64_mingw
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v4
        with:
          arch: ${{ matrix.arch }}
          version: 6.5.*
      - name: Compile
        run: |
          qmake
          make
        shell: bash
      - name: Test
        run: make check --keep-going
        shell: bash
